# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["lucasMezza_p1_dev"]
    # branches: ["lucasMezza_p1_base"]
  pull_request:
    branches: ["lucasMezza_p1_dev"]
    # branches: ["lucasMezza_p1_base"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-test-publish:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # ------------------------
      # BUILD

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build

      # ------------------------
      # TESTS

      - name: Create Tools Folder
        run: mkdir -p tools

      - name: Install ReSharper InspectCode
        run: dotnet tool install JetBrains.ReSharper.GlobalTools --tool-path tools

      - name: Run Code Inspection
        shell: powershell
        run: |
          $jbTool = (Resolve-Path "tools/jb.exe").Path
          $slnPath = (Resolve-Path "TrainProject.sln").Path
          Write-Host "Using jbTool: $jbTool"
          Write-Host "Using solution: $slnPath"
          cd myApp
          mkdir reports
          & "$jbTool" "inspectcode" "$slnPath" "-o=reports/report.xml" -f="xml"

      - name: Validate Inspection Report
        run: |
          cd scripts
          ./validate_report.ps1
        shell: powershell

      - name: Add Coverlet Package for Code Coverage
        run: |
          cd myApp.Tests
          mkdir -p reports
          dotnet add package coverlet.msbuild --package-directory .nuget

      - name: Run Unit Tests with Coverage
        run: |
          cd myApp.Tests
          dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=reports/coverage.cobertura.xml

      - name: Validate Code Coverage
        run: |
          cd scripts
          ./validate_coverage.ps1
        shell: powershell

      - name: Install ReportGenerator Tool
        run: dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools

      - name: Generate Coverage Report (HTML)
        shell: powershell
        run: |
          $reportTool = Resolve-Path "./tools/reportgenerator.exe"
          $reportFile = Resolve-Path "./myApp.Tests/reports/coverage.cobertura.xml"

          $outputDirPath = "./myApp.Tests/reports/coveragereport"
          if (-not (Test-Path $outputDirPath)) {
            New-Item -ItemType Directory -Path $outputDirPath | Out-Null
          }
          $outputDir = Resolve-Path $outputDirPath

          & "$reportTool" `
            "-reports:$reportFile" `
            "-targetdir:$outputDir" `
            "-reporttypes:Html"
          

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: myApp.Tests/reports/coveragereport

      # ------------------------
      # PUBLISH

      - name: Publish Application
        run: |
          dotnet publish myApp/myApp.csproj

      # ------------------------
      # DEPLOY
      
      - name: Deploy Application
        run: ./myApp/bin/Release/netcoreapp8/myApp

